version: '3.9'

services:
    backend:
      build: .
      ports:
        - 8000:8000
      volumes:
        - .:/usr/src/app
      depends_on:
        - mongodb
    
    mongodb:
      container_name: mongodb
      image: mongo:latest
      restart: always
      ports:
        - 2717:27017
      volumes:
        - mongodb:/data/db

volumes:
  mongodb: {}

