version: '3.9'

services:
    backend:
      build: .
      ports:
        - 8000:8000
      volumes:
        - .:/usr/src/app
      environments:
        - DATABASE_URL=mongodb://mongodb:27017
        - JWT_SECRET=hhfhfjdhjdhfjfjfjfhfjfjdx
      depends_on:
        - postgres
    
    postgres:
      container_name: postgres
      image: postgres:latest
      restart: always
      ports:
        - 5432:5432
      volumes:
        - ./db-data/:/var/lib/postgresql/data/

volumes:
  postgres: {}

